Getting values from configuration.json file
PractiTest/practitest-firecracker pull request #2
Opened 2019-12-05 10:15 UTC by shmuelko

configuration.json file will fill the fields (or replace the values from the user input) URI, email, project-id, API-token, and additional-test-fields.
Additionally, the values form the XML will be taken from all the available fields.

2020-01-29 16:55 UTC, stask requested changes

2020-01-29 16:55 UTC, stask commented on src/practitest_firecracker/cli.clj
> +    "Path to surefire cofiguration file"
Just `Path to configuration file` or `Path to firecracker configuration file`.

2020-01-29 16:55 UTC, stask commented on src/practitest_firecracker/cli.clj
> +    :parse-fn #(string/split % #"\s*,\s*")
This is only needed when the parameter is specified more than once (for reports paths for example). Configuration file can be specified only once.

2020-01-29 16:55 UTC, stask commented on src/practitest_firecracker/cli.clj
> +        parsed-json    (json/parse-string (first config-content) true)
you can do it in one line: `(json/parse-stream (reader <PATH>))`

2020-01-29 16:55 UTC, stask commented on src/practitest_firecracker/cli.clj
> +        options2 (merge options new-parsed-json)]
Why do you need `options2`? Just use `options (merge options new-parsed-json)`.

2020-01-29 16:59 UTC, shmuelko commented on src/practitest_firecracker/cli.clj
> +        parsed-json    (json/parse-string (first config-content) true)
you mean like this?: (json/parse-stream (reader (:config-path options)))

2020-01-29 17:00 UTC, shmuelko commented on src/practitest_firecracker/cli.clj
> +        options2 (merge options new-parsed-json)]
that was for debugging

2020-01-29 17:00 UTC, shmuelko commented on src/practitest_firecracker/cli.clj
> +    "Path to surefire cofiguration file"
Will fix

2020-01-29 17:00 UTC, shmuelko commented on src/practitest_firecracker/cli.clj
> +    :parse-fn #(string/split % #"\s*,\s*")
Will remove ":prase-fn"

2020-01-30 09:48 UTC, stask approved these changes

2020-01-30 09:57 UTC, merged